In [1]:
import pandas as pd

In [2]:
gs = pd.read_csv("total_review_gs_raw.csv")
nh = pd.read_csv("total_review_nh_raw.csv")
ys = pd.read_csv("total_review_ys_raw.csv")

In [3]:
total_review = pd.concat([gs, nh, ys], ignore_index=True)

In [4]:
total_review

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남더보기,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 1.5샷? 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만더보기,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,"트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데, 오히려 커피는 아쉬움더보기",4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다.더보기,5.0,2,5.0
17845,콘체르토,더보기,5.0,41,4.8
17846,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다.더보기,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페.인텔...,4.0,41,4.3
17848,바움,"콜드브루 5,5 와 진짜 찐하다.. 오늘 잠 못잘듯 ㅠ더보기",3.0,627,4.0

In [5]:
total_review.to_csv("가산동_논현동_역삼동_원본데이터셋_김희진.csv",encoding="utf-8-sig" ,index=False)

In [6]:
df_copy = total_review.copy()

In [7]:
df_copy = df_copy.drop_duplicates(['review'], keep = 'first') #중복제거
df_copy

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남더보기,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 1.5샷? 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만더보기,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,"트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데, 오히려 커피는 아쉬움더보기",4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17830,콘체르토,음악 들으면서 커피나 와인을 마실 수 있으니 예술의 전당보다 오히려 낫다.더보기,5.0,2,5.0
17831,콘체르토,"하우스와인 10, 과자랑 치즈 안주가 나온다. 클래식이 흘러나오는 따뜻한북카페더보기",5.0,627,4.0
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다.더보기,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페.인텔...,4.0,41,4.3
17848,바움,"콜드브루 5,5 와 진짜 찐하다.. 오늘 잠 못잘듯 ㅠ더보기",3.0,627,4.0

In [8]:
df_copy['review'] = df_copy['review'].str.replace('더보기','') 
#뒤에 붙은 '더보기' 제거

In [9]:
df_copy['review'] = df_copy['review'].str.replace('접기','')
#뒤에 붙은 '접기' 제거

In [10]:
df_copy['review'] = df_copy['review'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
#한글과 띄어쓰기 제외하고 모두 제거

C:\Users\heeji\AppData\Local\Temp/ipykernel_4456/3853512069.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_copy['review'] = df_copy['review'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

In [11]:
import warnings
warnings.filterwarnings("ignore")

In [12]:
df_copy

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 샷 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데 오히려 커피는 아쉬움,4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17830,콘체르토,음악 들으면서 커피나 와인을 마실 수 있으니 예술의 전당보다 오히려 낫다,5.0,2,5.0
17831,콘체르토,하우스와인 과자랑 치즈 안주가 나온다 클래식이 흘러나오는 따뜻한북카페,5.0,627,4.0
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페인텔리...,4.0,41,4.3
17848,바움,콜드브루 와 진짜 찐하다 오늘 잠 못잘듯 ㅠ,3.0,627,4.0

In [13]:
import numpy as np

In [14]:
df_copy['review'] = df_copy['review'].str.replace('^ +', "") # white space 데이터를 empty value로 변경
df_copy['review'].replace('', np.nan, inplace=True)
print(df_copy.isnull().sum())

name            0
review        105
star            0
review_num      0
ave_star        0
dtype: int64

In [15]:
df_copy.loc[df_copy.review.isnull()][:5]

                 name review  star review_num  ave_star
7    인크커피 가산 플래그십 스토어    NaN   4.0        253       3.5
135  인크커피 가산 플래그십 스토어    NaN   4.0      8,535       3.3
257       스타벅스 가산디지털점    NaN   1.0          2       1.0
268       스타벅스 가산디지털점    NaN   5.0          1       5.0
350     투썸플레이스 가산디지털점    NaN   4.0         88       3.4

In [16]:
df_copy = df_copy.dropna(how = 'any')

In [17]:
df_copy

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 샷 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데 오히려 커피는 아쉬움,4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17830,콘체르토,음악 들으면서 커피나 와인을 마실 수 있으니 예술의 전당보다 오히려 낫다,5.0,2,5.0
17831,콘체르토,하우스와인 과자랑 치즈 안주가 나온다 클래식이 흘러나오는 따뜻한북카페,5.0,627,4.0
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페인텔리...,4.0,41,4.3
17848,바움,콜드브루 와 진짜 찐하다 오늘 잠 못잘듯 ㅠ,3.0,627,4.0

In [18]:
df_copy['ave_star'] = pd.to_numeric(df_copy['ave_star'])

In [20]:
#긍정부정 라벨링

In [28]:
df_copy_drop = df_copy.drop(df_copy[(df_copy['star'] == 3) & (abs(df_copy['star']-df_copy['ave_star']) <= 1.5)].index)
#|(평균 평점-리뷰 평점)|≤1.5이면서 3점인 리뷰는 모두 삭제하기.

In [29]:
df_copy_drop

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 샷 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데 오히려 커피는 아쉬움,4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17829,콘체르토,웬만한 연주회 가는거 보다 나은거 같아요클래식음악과 대형스크린 대형스피커 어마무시한...,5.0,15,4.6
17830,콘체르토,음악 들으면서 커피나 와인을 마실 수 있으니 예술의 전당보다 오히려 낫다,5.0,2,5.0
17831,콘체르토,하우스와인 과자랑 치즈 안주가 나온다 클래식이 흘러나오는 따뜻한북카페,5.0,627,4.0
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페인텔리...,4.0,41,4.3

In [35]:
label = []
for i, j in zip(df_copy_drop['star'], df_copy_drop['ave_star']):
    if i >= 4:
        label.append('0')
    elif i <= 2:
        label.append('1')
    else:
        if abs(i-j) < -1.5:
            label.append('1')
        else:
            label.append('0')

In [36]:
df_copy_drop['label'] = label

In [37]:
df_copy_drop

,name,review,star,review_num,ave_star,label
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남,4.0,400,4.4,0
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 샷 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만,2.0,62,2.1,1
2,인크커피 가산 플래그십 스토어,트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데 오히려 커피는 아쉬움,4.0,25,4.1,0
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4,0
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0,1
...,...,...,...,...,...,...
17829,콘체르토,웬만한 연주회 가는거 보다 나은거 같아요클래식음악과 대형스크린 대형스피커 어마무시한...,5.0,15,4.6,0
17830,콘체르토,음악 들으면서 커피나 와인을 마실 수 있으니 예술의 전당보다 오히려 낫다,5.0,2,5.0,0
17831,콘체르토,하우스와인 과자랑 치즈 안주가 나온다 클래식이 흘러나오는 따뜻한북카페,5.0,627,4.0,0
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다,5.0,2,5.0,0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페인텔리...,4.0,41,4.3,0

In [39]:
df_copy_drop.to_csv("가산동_논현동_역삼동_최종데이터셋_김희진.csv",encoding="utf-8-sig" ,index=False)