In [ ]:
=>중복 제거
=>리뷰 없는 데이터 삭제
=>뒤에 붙은 ‘더보기’, ‘접기’ 삭제
=>영어 리뷰 삭제

-1, 2점: 무조건 부정/ 4, 5점: 무조건 긍정
3점: (리뷰별점-평균별점)>=1이면 긍정, 아니면 부정
리뷰가 1개이면서 리뷰별점이 3점인 사람은 무조건 날리기
평균별점이 2점 미만인 사람은 무조건 날리기


1. 오늘 밤까지 크롤링 완료
-윤서 님: 성수1동, 성수2동, 여의도동,
-상은 님: 명동, 삼성동, 서교동
-소연 님: 종로 1~4가동, 서초동, 청담동
-희진 님: 논현동, 가산동, 역삼동
2. 크롤링할 때 평균 별점, 리뷰 개수도 크롤링하기. 
3. 전처리 방식
-중복 제거/ 리뷰 없는 데이터 제거/ 뒤에 ‘더보기’, ‘접기’ 삭제/ 영어 리뷰 삭제
-악성댓글러(평균평점이 2점 미만인 경우) 삭제

In [76]:
import pandas as pd
import numpy as np

In [77]:
sg=pd.read_csv("total_seogyodong.csv")
sg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26928 entries, 0 to 26927
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        26928 non-null  object
 1   review      26928 non-null  object
 2   star        26928 non-null  float64
 3   review_num  26928 non-null  object
 4   ave_star    26928 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.0+ MB

In [78]:
my=pd.read_csv("total_myeongdong.csv")
my.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9891 entries, 0 to 9890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        9891 non-null   object
 1   review      9891 non-null   object
 2   star        9891 non-null   float64
 3   review_num  9891 non-null   object
 4   ave_star    9891 non-null   float64
dtypes: float64(2), object(3)
memory usage: 386.5+ KB

In [79]:
ss=pd.read_csv("total_samseongdong.csv")
ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6678 entries, 0 to 6677
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        6678 non-null   object
 1   review      6678 non-null   object
 2   star        6678 non-null   float64
 3   review_num  6678 non-null   object
 4   ave_star    6678 non-null   float64
dtypes: float64(2), object(3)
memory usage: 261.0+ KB

In [80]:
total=pd.concat([sg,my,ss],ignore_index=True)
total

,name,review,star,review_num,ave_star
0,피오니 홍대점,케이크 맛이쑤여..더보기,5.0,13,4.7
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요더보기,4.0,64,4.5
2,피오니 홍대점,"케익 4, 커피 2.더보기",3.0,210,3.1
3,피오니 홍대점,더보기,3.0,439,3.6
4,피오니 홍대점,진쟈 맛있어요.... 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ더보기,5.0,215,4.6
...,...,...,...,...,...
43492,카페르뷰,점심시간에 가서 35분 기다려서 음식 받음음식 맛도 쏘쏘... 다신 안가려구요......,1.0,6,3.0
43493,컴포즈커피 대치점,보통더보기,3.0,9,2.3
43494,컴포즈커피 대치점,더보기,4.0,863,3.8
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요. 텀블러쓰면 초콜렛 주십니다.더보기,5.0,36,3.8
43496,포타커피 강남포스코뒷점,더보기,3.0,200,3.0

# 중복, (더보기&접기) 공백 제거

In [81]:
total=total.drop_duplicates() #중복 제거
total=total[total['review']!="더보기"] #리뷰없는 데이터 제거
total['review']=total['review'].str.replace('더보기','') #더보기 제거
total['review']=total['review'].str.replace('접기','') #접기 제거
total=total[total['review']!=""]
total

,name,review,star,review_num,ave_star
0,피오니 홍대점,케이크 맛이쑤여..,5.0,13,4.7
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요,4.0,64,4.5
2,피오니 홍대점,"케익 4, 커피 2.",3.0,210,3.1
4,피오니 홍대점,진쟈 맛있어요.... 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ,5.0,215,4.6
7,피오니 홍대점,커피가 너무 맛없어요 ㅠㅠ 딸기케익은 여전한 맛입니다. 매장 안에 화장실 있어서 편해요.,4.0,73,3.9
...,...,...,...,...,...
43486,아리스타커피 선릉점,무화과쥬스 존맛,5.0,6,3.2
43491,매머드익스프레스 포스코센터점,☕️,5.0,25,1.6
43492,카페르뷰,점심시간에 가서 35분 기다려서 음식 받음음식 맛도 쏘쏘... 다신 안가려구요....,1.0,6,3.0
43493,컴포즈커피 대치점,보통,3.0,9,2.3
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요. 텀블러쓰면 초콜렛 주십니다.,5.0,36,3.8

# 영어 포함된 리뷰 제거

In [82]:
total['review'] = total['review'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","",regex=True) 
total=total[total['review']!=""]
total

,name,review,star,review_num,ave_star
0,피오니 홍대점,케이크 맛이쑤여,5.0,13,4.7
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요,4.0,64,4.5
2,피오니 홍대점,케익 커피,3.0,210,3.1
4,피오니 홍대점,진쟈 맛있어요 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ,5.0,215,4.6
7,피오니 홍대점,커피가 너무 맛없어요 ㅠㅠ 딸기케익은 여전한 맛입니다 매장 안에 화장실 있어서 편해요,4.0,73,3.9
...,...,...,...,...,...
43485,아리스타커피 선릉점,쥬스종류가 다양하고 다 맛있었어요 무화과랑 바나나케일 넘나 맛남 안쪽 자리도 넓어서...,4.0,1,4.0
43486,아리스타커피 선릉점,무화과쥬스 존맛,5.0,6,3.2
43492,카페르뷰,점심시간에 가서 분 기다려서 음식 받음음식 맛도 쏘쏘 다신 안가려구요,1.0,6,3.0
43493,컴포즈커피 대치점,보통,3.0,9,2.3
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요 텀블러쓰면 초콜렛 주십니다,5.0,36,3.8

# 전처리 완료

In [83]:
total

,name,review,star,review_num,ave_star
0,피오니 홍대점,케이크 맛이쑤여,5.0,13,4.7
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요,4.0,64,4.5
2,피오니 홍대점,케익 커피,3.0,210,3.1
4,피오니 홍대점,진쟈 맛있어요 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ,5.0,215,4.6
7,피오니 홍대점,커피가 너무 맛없어요 ㅠㅠ 딸기케익은 여전한 맛입니다 매장 안에 화장실 있어서 편해요,4.0,73,3.9
...,...,...,...,...,...
43485,아리스타커피 선릉점,쥬스종류가 다양하고 다 맛있었어요 무화과랑 바나나케일 넘나 맛남 안쪽 자리도 넓어서...,4.0,1,4.0
43486,아리스타커피 선릉점,무화과쥬스 존맛,5.0,6,3.2
43492,카페르뷰,점심시간에 가서 분 기다려서 음식 받음음식 맛도 쏘쏘 다신 안가려구요,1.0,6,3.0
43493,컴포즈커피 대치점,보통,3.0,9,2.3
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요 텀블러쓰면 초콜렛 주십니다,5.0,36,3.8

# 긍/부정 판별

In [84]:
label=[
    (total['star']>=4),
    (total['star']<=2),
    (total['star']==3) & (total['star']-total['ave_star']>1.5),
    (total['star']==3) & (total['star']-total['ave_star']<-1.5),
    (total['star']==3) & (total['ave_star']-total['star']>=1.5),
    (total['star']==3) & (total['ave_star']-total['star']<=1.5),]

labelling=[0,1,0,1,2,2]

total['label']=np.select(label,labelling,default='Not specified')

C:\Users\jse17\AppData\Local\Temp/ipykernel_13164/2068470097.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total['label']=np.select(label,labelling,default='Not specified')

In [98]:
total=total[total['label']!="2"]
total

,name,review,star,review_num,ave_star,label
0,피오니 홍대점,케이크 맛이쑤여,5.0,13,4.7,0
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요,4.0,64,4.5,0
4,피오니 홍대점,진쟈 맛있어요 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ,5.0,215,4.6,0
7,피오니 홍대점,커피가 너무 맛없어요 ㅠㅠ 딸기케익은 여전한 맛입니다 매장 안에 화장실 있어서 편해요,4.0,73,3.9,0
23,피오니 홍대점,어쩌다 홍대 관광명소가 됐는데 웨이팅 고생하지말고 테이크아웃 추천딸기빙수는 시럽맛이...,3.0,45,4.6,1
...,...,...,...,...,...,...
43484,아리스타커피 선릉점,바나나케일 맛있어요,5.0,4,5.0,0
43485,아리스타커피 선릉점,쥬스종류가 다양하고 다 맛있었어요 무화과랑 바나나케일 넘나 맛남 안쪽 자리도 넓어서...,4.0,1,4.0,0
43486,아리스타커피 선릉점,무화과쥬스 존맛,5.0,6,3.2,0
43492,카페르뷰,점심시간에 가서 분 기다려서 음식 받음음식 맛도 쏘쏘 다신 안가려구요,1.0,6,3.0,1
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요 텀블러쓰면 초콜렛 주십니다,5.0,36,3.8,0

In [99]:
total.to_csv('total_labelling.csv',encoding='utf-8-sig',index=False)