## 데이터 불러오기

In [2]:
import pandas as pd

In [3]:
sung1_df=pd.read_csv("total_review_성수1동_후기개수버전.csv")

In [4]:
sung1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26844 entries, 0 to 26843
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        26844 non-null  object
 1   review      26844 non-null  object
 2   star        26844 non-null  float64
 3   review_num  26844 non-null  object
 4   ave_star    26844 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.0+ MB

In [5]:
sung2_df=pd.read_csv("total_review_성수2동_후기개수버전.csv")

In [6]:
sung2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25253 entries, 0 to 25252
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        25253 non-null  object
 1   review      25253 non-null  object
 2   star        25253 non-null  float64
 3   review_num  25253 non-null  object
 4   ave_star    25253 non-null  float64
dtypes: float64(2), object(3)
memory usage: 986.6+ KB

In [7]:
yo_df=pd.read_csv("total_review_여의도.csv")

In [8]:
yo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9803 entries, 0 to 9802
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        9803 non-null   object
 1   review      9803 non-null   object
 2   star        9803 non-null   float64
 3   review_num  9803 non-null   object
 4   ave_star    9803 non-null   float64
dtypes: float64(2), object(3)
memory usage: 383.1+ KB

## 데이터 합치기

In [9]:
df=pd.concat([sung1_df,sung2_df,yo_df],ignore_index=True)

In [10]:
#df.to_csv("성수동_여의도동_원본데이터셋_최윤서.csv",index=False, encoding='utf-8-sig') #데이터 저장

## 중복제거

In [10]:
df

,name,review,star,review_num,ave_star
0,블루보틀 성수 카페,더보기,1.0,499,3.7
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음더보기,3.0,15,4.7
2,블루보틀 성수 카페,나라마다 맛 다르던데 여기는 맛없는 편 아이스라떼기준일하시는 분들은 너무너무 친절하...,3.0,16,3.6
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈. 커피는 맛있음.더보기,4.0,83,3.7
4,블루보틀 성수 카페,놀라 아스크림 쫀쫀 고소 맛있어용더보기,3.0,401,3.8
...,...,...,...,...,...
61895,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0
61896,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람.더보기,5.0,29,4.2
61897,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고더보기,4.0,10,1.9
61898,설빙 노량진점,체육관 2개와 포켓스탑 1개 잡힘.영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여...,4.0,318,3.4
61899,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3

In [29]:
df_1=df.drop_duplicates()

## 리뷰 없는 데이터 제거

In [30]:
df_2=df_1[df_1["review"]!="더보기"]

In [31]:
df_2

,name,review,star,review_num,ave_star
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음더보기,3.0,15,4.7
2,블루보틀 성수 카페,나라마다 맛 다르던데 여기는 맛없는 편 아이스라떼기준일하시는 분들은 너무너무 친절하...,3.0,16,3.6
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈. 커피는 맛있음.더보기,4.0,83,3.7
4,블루보틀 성수 카페,놀라 아스크림 쫀쫀 고소 맛있어용더보기,3.0,401,3.8
6,블루보틀 성수 카페,맛있고 친절해욘더보기,4.0,31,3.6
...,...,...,...,...,...
61869,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0
61870,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람.더보기,5.0,29,4.2
61871,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고더보기,4.0,10,1.9
61872,설빙 노량진점,체육관 2개와 포켓스탑 1개 잡힘.영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여...,4.0,318,3.4
61893,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3

In [32]:
df_3=df_2.copy()

## 뒤에 "더보기", "접기" 삭제

In [33]:
df_3["review"].replace('더보기$',"",inplace=True,regex=True)

In [34]:
df_3["review"].replace('접기$',"",inplace=True,regex=True)

In [35]:
df_3

,name,review,star,review_num,ave_star
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음,3.0,15,4.7
2,블루보틀 성수 카페,나라마다 맛 다르던데 여기는 맛없는 편 아이스라떼기준일하시는 분들은 너무너무 친절하...,3.0,16,3.6
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈. 커피는 맛있음.,4.0,83,3.7
4,블루보틀 성수 카페,놀라 아스크림 쫀쫀 고소 맛있어용,3.0,401,3.8
6,블루보틀 성수 카페,맛있고 친절해욘,4.0,31,3.6
...,...,...,...,...,...
61869,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0
61870,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람.,5.0,29,4.2
61871,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고,4.0,10,1.9
61872,설빙 노량진점,체육관 2개와 포켓스탑 1개 잡힘.영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여...,4.0,318,3.4
61893,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3

In [36]:
df_4=df_3.copy()

## 영어 리뷰 삭제

In [37]:
df_4['review'] = df_4['review'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","") #한글만 남기기.

C:\Users\sycy0\AppData\Local\Temp\ipykernel_5956\2801449901.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_4['review'] = df_4['review'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","") #한글만 남기기.

In [39]:
df_5=df_4.copy() #df_4: 영어 리뷰 삭제

## 공백으로만 이루어진 리뷰 제거

In [40]:
df_5["review"].replace('\s*$',"",inplace=True,regex=True) #공백으로만 이루어진 거 제거

In [41]:
df_5=df_5[~(df_5["review"]=="")] #리뷰 길이가 0인 거 제거.

In [42]:
df_5=df_5.drop_duplicates() #중복 제거

In [43]:
df_5["positive?"]=""
df_5.loc[df_5.star>=4,"positive?"]=0 #4, 5점은 긍정으로
df_5.loc[df_5.star<=2,"positive?"]=1 #1, 2점은 부정으로
df_5=df_5.loc[~((df_5.star==3) & (abs(df_5.star-df_5.ave_star)<=1.5)),:] #3점 중 리뷰 평점이랑 평균 평점의 차이가 1.5 이하인 건 삭제
df_5

,name,review,star,review_num,ave_star,positive?
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음,3.0,15,4.7,
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈 커피는 맛있음,4.0,83,3.7,0
6,블루보틀 성수 카페,맛있고 친절해욘,4.0,31,3.6,0
7,블루보틀 성수 카페,뭐 얼마나 그렇게 비싼거 먹었다고 고나리질하는 댓글들만 가득한지 모르겠네요매장이 바...,5.0,1,5.0,0
28,블루보틀 성수 카페,오후 시에 갔는데 자리가 없을정도로 자리도 별로 없고 사람이 붐비지만 커피는 굿굿 ...,4.0,97,4.6,0
...,...,...,...,...,...,...
61869,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0,1
61870,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람,5.0,29,4.2,0
61871,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고,4.0,10,1.9,0
61872,설빙 노량진점,체육관 개와 포켓스탑 개 잡힘영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여기는 ...,4.0,318,3.4,0
61893,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3,0

In [44]:
df_5.loc[(df_5.star-df_5.ave_star)>1.5,"positive?"]=0
df_5.loc[(df_5.star-df_5.ave_star)<-1.5,"positive?"]=1
df_5

,name,review,star,review_num,ave_star,positive?
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음,3.0,15,4.7,1
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈 커피는 맛있음,4.0,83,3.7,0
6,블루보틀 성수 카페,맛있고 친절해욘,4.0,31,3.6,0
7,블루보틀 성수 카페,뭐 얼마나 그렇게 비싼거 먹었다고 고나리질하는 댓글들만 가득한지 모르겠네요매장이 바...,5.0,1,5.0,0
28,블루보틀 성수 카페,오후 시에 갔는데 자리가 없을정도로 자리도 별로 없고 사람이 붐비지만 커피는 굿굿 ...,4.0,97,4.6,0
...,...,...,...,...,...,...
61869,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0,1
61870,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람,5.0,29,4.2,0
61871,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고,4.0,10,1.9,0
61872,설빙 노량진점,체육관 개와 포켓스탑 개 잡힘영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여기는 ...,4.0,318,3.4,0
61893,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3,0

In [45]:
df_5=df_5.reset_index(drop=True) #인덱스 바꿔주기

In [46]:
df_5.to_csv("최종데이터셋_성수동_여의도동_최윤서.csv",encoding='utf-8-sig',index=False)