## 김희진 - 가산동/논현동/역삼동

## 지상은 - 서교동/명동/삼성동

## 박소연 - 서초동/종로1234가동/압구정동

## 최윤서 - 성수동/여의도동

# 원본데이터셋 !!

In [1]:
import pandas as pd

In [47]:
kim1=pd.read_csv('가산동_논현동_역삼동_원본데이터셋_김희진.csv')
ji1=pd.read_csv('서교동_명동_삼성동_원본데이터셋_지상은.csv')
park1=pd.read_csv('서초동_종로1234가동_압구정동_원본데이터셋_박소연.csv')
choi1=pd.read_csv('성수동_여의도동_원본데이터셋_최윤서.csv')

In [48]:
kim1

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남더보기,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 1.5샷? 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만더보기,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,"트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데, 오히려 커피는 아쉬움더보기",4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
17844,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다.더보기,5.0,2,5.0
17845,콘체르토,더보기,5.0,41,4.8
17846,콘체르토,마음에 들지 않는것을 찾기 어려운게 문제입니다.더보기,5.0,2,5.0
17847,바움,엉성한 느낌이 들기도 하지만 강남역에서 비교적 차분한 분위기의 화이트 톤 카페.인텔...,4.0,41,4.3
17848,바움,"콜드브루 5,5 와 진짜 찐하다.. 오늘 잠 못잘듯 ㅠ더보기",3.0,627,4.0

In [49]:
ji1

,name,review,star,review_num,ave_star
0,피오니 홍대점,케이크 맛이쑤여..더보기,5.0,13,4.7
1,피오니 홍대점,케이크가 특별히 엄청 맛있는지는 모르겠어요 평범한 딸케에요더보기,4.0,64,4.5
2,피오니 홍대점,"케익 4, 커피 2.더보기",3.0,210,3.1
3,피오니 홍대점,더보기,3.0,439,3.6
4,피오니 홍대점,진쟈 맛있어요.... 사람 많아도 포장 추천 홀케이크 먹고싶다 ㅍ더보기,5.0,215,4.6
...,...,...,...,...,...
43492,카페르뷰,점심시간에 가서 35분 기다려서 음식 받음음식 맛도 쏘쏘... 다신 안가려구요......,1.0,6,3.0
43493,컴포즈커피 대치점,보통더보기,3.0,9,2.3
43494,컴포즈커피 대치점,더보기,4.0,863,3.8
43495,컴포즈커피 대치점,친절하고 샷도 바로 뽑아 바로 주시고요. 텀블러쓰면 초콜렛 주십니다.더보기,5.0,36,3.8
43496,포타커피 강남포스코뒷점,더보기,3.0,200,3.0

In [50]:
park1=park1.drop(['Unnamed: 0'],axis=1)
park1=park1.rename(columns={'store_name':'name','id_count':'review_num','id_star':'ave_star'})
park1

,name,review,star,review_num,ave_star
0,프릳츠 양재점,빵들은 여전히 맛있으나 커피맛이 너무 평범해져서 아쉽습니다. 1층에 앉아있는 손님들...,3.0,8,4.0
1,프릳츠 양재점,의자가 심각하게 삐걱거려요.위에 커피 올려 놓으면 엎지를 가능성 100%.더보기,2.0,54,2.4
2,프릳츠 양재점,더보기,5.0,145,4.2
3,프릳츠 양재점,블루베리 파이 맛집더보기,5.0,186,4.8
4,프릳츠 양재점,더보기,5.0,1,5.0
...,...,...,...,...,...
51634,설빙 가로수길점,더보기,1.0,1,1.0
51635,설빙 가로수길점,일점이 아까울 수도 있네요.더보기,1.0,3,3.7
51636,설빙 가로수길점,설빙이 어케 1점이지 뭐가 다르겠어하고 갔다가 왜 1점인지 알겠다 .. 빙수 잘못나...,1.0,42,3.7
51637,설빙 가로수길점,더보기,1.0,2,1.0
51638,설빙 가로수길점,더보기,1.0,6,2.7

In [51]:
choi1

,name,review,star,review_num,ave_star
0,블루보틀 성수 카페,더보기,1.0,499,3.7
1,블루보틀 성수 카페,커피 맛도 그저 그렇고 분위기도 인상 깊지 않아서 아쉬웠음더보기,3.0,15,4.7
2,블루보틀 성수 카페,나라마다 맛 다르던데 여기는 맛없는 편 아이스라떼기준일하시는 분들은 너무너무 친절하...,3.0,16,3.6
3,블루보틀 성수 카페,커피는 뭐 딱히 안찍었고 굿즈가 진짜 너무 비쌈. 커피는 맛있음.더보기,4.0,83,3.7
4,블루보틀 성수 카페,놀라 아스크림 쫀쫀 고소 맛있어용더보기,3.0,401,3.8
...,...,...,...,...,...
61895,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0
61896,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람.더보기,5.0,29,4.2
61897,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고더보기,4.0,10,1.9
61898,설빙 노량진점,체육관 2개와 포켓스탑 1개 잡힘.영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여...,4.0,318,3.4
61899,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3

In [52]:
df_crawling=pd.concat([kim1,ji1,park1,choi1],ignore_index=True)

In [53]:
df_crawling

,name,review,star,review_num,ave_star
0,인크커피 가산 플래그십 스토어,대형 카페 그잡채빵들이 너무 맛있다 커피 독특한데 맛남더보기,4.0,400,4.4
1,인크커피 가산 플래그십 스토어,이 가격에 이 용량에 1.5샷? 싸장님 맘이라지만 ㅎㅎㅎ 한번 가본걸로 이만더보기,2.0,62,2.1
2,인크커피 가산 플래그십 스토어,"트리보러 가는 곳넓은데 사람 많음빵은 다 맛있었는데, 오히려 커피는 아쉬움더보기",4.0,25,4.1
3,인크커피 가산 플래그십 스토어,동네라 자주 가는데 어쩔땐 친절하고 어쩔땐 불친절하고 알바바이알바인듯 ㅋㅋㅋ 근데 ...,4.0,90,3.4
4,인크커피 가산 플래그십 스토어,카페 분위기는 좋으나 디저트 준비하는 곳에서 일하시는 여자 알바가 너무 싸가지 없어...,1.0,1,1.0
...,...,...,...,...,...
174880,설빙 노량진점,노량진점 설빙 진짜별로네요 최악이에요 고객한테 대하는 전화 말투법이 상당히 거칠고 ...,1.0,2,1.0
174881,설빙 노량진점,배달 시켰는데 다른 지점보다 양이 많아서 놀람.더보기,5.0,29,4.2
174882,설빙 노량진점,맛잇음 다른 설빙 가게들보다 양도 많은거 같고더보기,4.0,10,1.9
174883,설빙 노량진점,체육관 2개와 포켓스탑 1개 잡힘.영등포 설빙은 시설도 빙수 퀄리티도 최악인데 여...,4.0,318,3.4
174884,설빙 노량진점,학생들을 위한 배려인건지는 모르겠으나 설빙 다른 지점보다 토핑이나 재료를 후하게 얹...,4.0,26,3.3

In [55]:
df_crawling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174885 entries, 0 to 174884
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   name        174885 non-null  object
 1   review      174885 non-null  object
 2   star        174885 non-null  float64
 3   review_num  174885 non-null  object
 4   ave_star    174885 non-null  float64
dtypes: float64(2), object(3)
memory usage: 6.7+ MB

In [57]:
df_crawling.to_csv('df_crawling.csv',encoding='utf-8-sig',index=False)